name: Manual Scrap Workflow

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      run: |
        pip install requests jsonlib re os shutil datetime pillow

    - name: Run Python Script
      run: python3 _scrapper/scrap.py

    - name: Git setup
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit and Push
      run: |
        git add -A
        git commit -m "Automated run of scrap.py"
        git push
